name: tfupdate

on:
  push:
    branches:
      - feature/tfupdate

jobs:
  tfupdate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Docker Build
      run: |
        docker build -t tfupdate -f Dockerfile.tfupdate .
    - name: Terraform Update
      run: |
        docker run \
          -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
          -e BASE_BRANCH=${BASE_BRANCH} \
          -e GITHUB_USER=ut-ymmt \
          --entrypoint "./update-terraform.sh" \
          tfupdate
      env:
        BASE_BRANCH: "feature/tfupdate"
